---
title: C28105
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 148682fef26be86e4b91db87d74c2ac2f78d69e2
ms.sourcegitcommit: e13e61ddea6032a8282abe16131d9e136a927984
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 04/26/2018
ms.locfileid: "31888409"
---
# <a name="c28105"></a>C28105
Aviso C28105: Vazamento de recursos devido a uma exceção

 O recurso especificado não é liberado quando uma exceção é gerada. A instrução especificada pelo caminho pode gerar uma exceção. Esse aviso é semelhante ao aviso [C28103](../code-quality/c28103.md), exceto que, nesse caso uma exceção está envolvida.

## <a name="example"></a>Exemplo
 O exemplo de código a seguir gera este aviso:

```
res = KeSaveFloatingPointState(buffer);

res = AllocateResource(Resource);
char *p2 = new char[10]; // could throw

delete[] p2;
FreeResource(Resource)
```

 O exemplo de código a seguir evita este aviso:

```
res = AllocateResource(Resource);
char *p2;

try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
FreeResource(Resource)
```